### ISSUE TITLE
Undeclared dependencies

### ISSUE THREAD

**Issue by eserte** [JEEN/p5-WWW-Shorten-Naver#1]
It seems that WWW::Shorten::generic and Moo should be declared as prerequisites; otherwise I see test failures on my smoker systems.

**Comment by JEEN** [comment]
@eserte Oops, I was my fault. Just fixed it and released again

**Comment by eserte** [comment]
I see that Moo has gone, but WWW::Shorten::generic is still undeclared.

**Comment by eserte** [comment]
Also I found another undeclared dependency: JSON::MaybeXS (used in lib/WWW/Shorten/Naver.pm line 5)

**Comment by Grinnz** [comment]
The dependencies WWW::Shorten::generic, JSON::MaybeXS, and URI should be added to the cpanfile for Minilla to use

**Comment by JEEN** [comment]
@eserte , @Grinnz There was a lot of mistake. I just fixed it.
